[15기 김순태] Add: Password & Phone_number 변경 기능 구현
wecode-bootcamp-korea/15-2nd-we_ro-backend pull request #13
Opened 2021-01-04 11:12 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 유저 information 변경 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- current_password 확인 후 new_password 변경
- current_password 확인 후 new_phone_number 변경
- signin decorator
- test 코드 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-04 11:52 UTC, kst6294 commented
![image](https://user-images.githubusercontent.com/44313290/103532472-a39ae900-4ece-11eb-897d-256325cf77ae.png)

[1] 기존의 패스워드가 같은지 확인, [2] 패스워드가 같으면 패스워드 변경 실패, [3] 패스워드가 다르면 패스워드 변경, [4] 휴대폰 번호 변경

2021-01-05 06:47 UTC, lordmyshepherd requested changes

2021-01-05 06:47 UTC, lordmyshepherd commented on user/utils.py
> +        return JsonResponse({'MESSAGE' : 'INVALID_PHONE_NUMBER_TYPE'}, status=400)
`isinstance()` 사용하여, True, False 값을 반환 받아서 사용할 수 있습니다.

```suggestion
    if not isinstance(data['email'], str):
        return JsonResponse({'MESSAGE' : 'INVALID_EMAIL_TYPE'}, status=400)
    if not isinstance(data['password'], str):
        return JsonResponse({'MESSAGE' : 'INVALID_PASSWORD_TYPE'}, status=400)
```

2021-01-05 06:47 UTC, lordmyshepherd commented on user/utils.py
> +            signed_user  = User.objects.get(id=payload['id'])
아래 코드에 대한 예외처리가 필요할 것 같습니다.
```suggestion
            signed_user  = User.objects.get(id=payload['id'])
```

2021-01-05 06:47 UTC, lordmyshepherd commented on user/views.py
> +            signed_user  = User.objects.get(id=user_id)
`get()` 호출 시 matching되는 데이터가 없을 경우 어떤 에러가 발생하나요?
```suggestion
            signed_user  = User.objects.get(id=user_id)
```

2021-01-05 06:47 UTC, lordmyshepherd commented on user/views.py
> +class PasswordCheckView(View):
해당 엔드포인트는 언제 사용되는 건가요?

2021-01-05 06:47 UTC, lordmyshepherd commented on user/views.py
> +        except ValueError:
value error는 언제 발생하나요?

2021-01-05 06:47 UTC, lordmyshepherd commented on user/tests.py
> +        client = Client()
client 객체를 매번 생성해주는 이유가 있나요?

2021-01-05 06:47 UTC, lordmyshepherd commented on user/tests.py
> +        client = Client(HTTP_Authorization = self.access_token)
```suggestion
```

2021-01-05 06:47 UTC, lordmyshepherd commented on user/tests.py
> +        response = client.post('/users/password/check', json.dumps(user), content_type='application/json')
가독성을 위해서 `headers`를 post 인자로 전달해주세요~
```suggestion
        response = client.post('/users/password/check', json.dumps(user), content_type='application/json', headers=...)
```

2021-01-05 07:01 UTC, kst6294 commented on user/utils.py
> +        return JsonResponse({'MESSAGE' : 'INVALID_PHONE_NUMBER_TYPE'}, status=400)
반영했습니다. 감사합니다!

2021-01-05 07:01 UTC, kst6294 commented on user/utils.py
> +            signed_user  = User.objects.get(id=payload['id'])
반영했습니다!

2021-01-05 07:01 UTC, kst6294 commented on user/views.py
> +            signed_user  = User.objects.get(id=user_id)
User matching query does not exist. 발생합니다.

햬당 경우 예외처리 반영했습니다.

2021-01-05 07:03 UTC, kst6294 commented on user/views.py
> +class PasswordCheckView(View):
패스워드, 휴대폰 번호 변경시에 패스워드를 체크하는 상황에서 사용 됩니다.

![image](https://user-images.githubusercontent.com/44313290/103616288-794d3800-4f6f-11eb-877f-e7e9ef7f82a7.png)

2021-01-05 07:05 UTC, kst6294 commented on user/views.py
> +        except ValueError:
새롭게 받는 new_password 의 타입이 str 아닐 때 발생합니다.
new_phone_number 도 동일 합니다.

해당 예외처리 utils.py 에 추가 반영했습니다.

2021-01-05 07:06 UTC, kst6294 commented on user/tests.py
> +        client = Client()
처음 작성시에 빈 client 객체를 필수적으로 생성해야 하는 줄 알았으나, 여러개의 header를 동시에 추가해야하는 상황에서 client 객체를 하나만 생성하고 여러개의 파라미터를 담을 수 있는 것을 알게 됐습니다.

반영했습니다.

2021-01-05 07:06 UTC, kst6294 commented on user/tests.py
> +        client = Client(HTTP_Authorization = self.access_token)
반영했습니다.

2021-01-05 07:29 UTC, kst6294 commented on user/tests.py
> +        response = client.post('/users/password/check', json.dumps(user), content_type='application/json')
반영했습니다.

이런 좋은 방법을....

2021-01-06 07:23 UTC, lordmyshepherd approved these changes

2021-01-06 07:23 UTC, lordmyshepherd commented
LGTM 👍

2021-01-06 07:24 UTC, merged