[15기 김순태] Add: Character 기능 구현
wecode-bootcamp-korea/15-2nd-we_ro-backend pull request #14
Opened 2021-01-05 00:44 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- 캐릭터 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- character create
- character delete
- character update name / image
- tests.py
- 
![image](https://user-images.githubusercontent.com/44313290/103593890-6409e680-4f3a-11eb-9474-c5a865346061.png)

테스트: [1] get 캐릭터 api, [2] post  캐릭터 생성, [3] delete 캐릭터 삭제, [4] patch 캐릭터 이름 업데이트, [5] patch 캐릭터 이미지 업데이트

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-05 07:02 UTC, lordmyshepherd requested changes

2021-01-05 07:02 UTC, lordmyshepherd commented on user/utils.py
> +def SignInAuthorization(function):
해당 코드가 이전 pr에도 있던 것 같은데 왜 올라온걸까요??

2021-01-05 07:02 UTC, lordmyshepherd commented on user/views.py
> +            name_validation = Character.objects.select_related('user').filter(user_id=signed_user.id).filter(name=name)
select_related('user')를 사용하신 이유가 뭔가요?

2021-01-05 07:02 UTC, lordmyshepherd commented on user/views.py
> +            character = Character.objects.select_related('user').filter(user_id=signed_user.id).filter(id=character_id).get()
마찬가지로 select_related()를 사용하신 이유가 궁굼해요~

2021-01-05 07:02 UTC, lordmyshepherd commented on user/views.py
> +class CharacterUpdateNameView(View):
`class CharacterUpdateNameView(View)`와 `class CharacterUpdateImageView`는 `class CharacterView`에 하나의 patch()에서 구현될 수 있도록 수정해주세요.
patch()는 데이터를 부분적으로 업데이트 한다는 의미를 가지고 있습니다. 그렇기 때문에 하나의 Character 엔드포인트에서 `name`, `image` 별로 부분적으로 업데이트가 가능하도록 기능을 구현해주셔야 합니다.

2021-01-05 10:43 UTC, kst6294 commented on user/utils.py
> +def SignInAuthorization(function):
main branch 의 user/utils.py 에는 해당 코드가 작성되어 있지 않아있고, feature/character 브랜치에도 valueerror 와 signinauthorization 을 사용해야 해서 동일하게 작성했었습니다.

2021-01-05 10:43 UTC, kst6294 commented on user/views.py
> +            name_validation = Character.objects.select_related('user').filter(user_id=signed_user.id).filter(name=name)
다른 부분에서 select_related 를 활용하려고 작성하다가 이번 코드에 적용한 것 같습니다.

shell 에서 select_related 를 사용하지 않고도 정상 작동하는 것을 확인 했고, 수정 반영 했습니다.

2021-01-05 10:43 UTC, kst6294 commented on user/views.py
> +            character = Character.objects.select_related('user').filter(user_id=signed_user.id).filter(id=character_id).get()
위의 답변과 동일 합니다.

수정 반영 했습니다.

2021-01-05 10:43 UTC, kst6294 commented on user/views.py
> +class CharacterUpdateNameView(View):
반영했습니다.

2021-01-06 07:25 UTC, kst6294 commented
충돌 해결하겠습니다~!

2021-01-06 07:53 UTC, lordmyshepherd requested changes

2021-01-06 07:53 UTC, lordmyshepherd commented on user/views.py
> +                return JsonResponse({'MESSAGE' : 'CHARACTER_NAME_EXISTS'}, status=400)
```suggestion
            if Character.objects.filter(user_id=signed_user.id, name=name).exists():
                return JsonResponse({'MESSAGE' : 'CHARACTER_NAME_EXISTS'}, status=400)
```

2021-01-06 07:53 UTC, lordmyshepherd commented on user/views.py
> +            character.save()
```suggestion
            if Character.objects.filter(id=character_id, user_id=signed_user.id).exists():
                    character = Character.objects.get(id=character_id, user_id=signed_user.id)
                    character.name = new_name
                    character. profile_image_url = new_image
                    character.save()
```

2021-01-06 07:53 UTC, lordmyshepherd commented on user/views.py
> +            return JsonResponse({'MESSAGE' : 'INVALID_KEY'}, status=400)
위 코드에서는 keyerror가 발생하지 않을 것 같습니다.

2021-01-06 07:53 UTC, lordmyshepherd commented on user/views.py
> +            new_image = data.get('new_image')
아래 keyerror를 잡아주셨으면, 아래와 같이 접근해야 됩니다.
` new_name  = data['new_name']`

2021-01-06 08:11 UTC, kst6294 commented on user/views.py
> +            new_image = data.get('new_image')
new_name 과 new_image 가 동시에 진행되지 않고, 개별적으로 작동해야하는데, data['new_name], data['new_image'] 로 진행할 경우 예상한 결과가 나오지 않아, get method 를 사용했습니다.

예를 들어, 하나의 view 에서 new_name 만 들어오거나 new_image 만 들어 갈 수 있습니다.

조건문을 달아도 값이 하나만 전달 되는 경우에 에러 발생을 피할 수 없다고 판단 했는데,
위와 같은 경우에도 data['new_name'] 접근 방식으로 진행해야 하는 지요?

2021-01-06 08:12 UTC, kst6294 commented on user/views.py
> +            return JsonResponse({'MESSAGE' : 'INVALID_KEY'}, status=400)
반영했습니다.

2021-01-06 08:28 UTC, kst6294 commented on user/views.py
> +            character.save()
반영했습니다.

2021-01-06 08:28 UTC, kst6294 commented on user/views.py
> +                return JsonResponse({'MESSAGE' : 'CHARACTER_NAME_EXISTS'}, status=400)
반영했습니다.

2021-01-06 08:45 UTC, lordmyshepherd commented on user/views.py
> +            new_image = data.get('new_image')
이해 했습니다!
그렇다면 아래 `KeyError`를 핸들링해 줄 필요가 없어 보입니다.

2021-01-06 10:53 UTC, lordmyshepherd approved these changes

2021-01-06 10:54 UTC, lordmyshepherd commented
LGTM 👍

2021-01-06 10:54 UTC, merged