[15기 김순태] Add: Mylist, Mylist_Music 기능 구현
wecode-bootcamp-korea/15-2nd-we_ro-backend pull request #16
Opened 2021-01-06 03:23 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- mylist 생성 및 수정, mylist_music 추가 및 api 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- mylist create
- mylist delete
- mylist update name
- MylistMusic API
- Add list of Musices into Mylist
- Test code 작성

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-07 02:20 UTC, lordmyshepherd requested changes

2021-01-07 02:20 UTC, lordmyshepherd commented on storage/tests.py
> +        headers = {'HTTP_Authorization' : self.access_token, 'HTTP_Character' : self.character_id}
character_id를 headers에 담아서 념겨주는 이유가 있나요?

```suggestion
        headers = {'HTTP_Authorization' : self.access_token, 'HTTP_Character' : self.character_id}
```

2021-01-07 02:20 UTC, lordmyshepherd commented on storage/tests.py
> +            gender=Gender.objects.get(id=1),
위애서 `ArtistType.objects.create(id=1, name='솔로')` 코드가 실행되면서 데이터를 생성하고 객체를 반환받는데 이 값을 사용하는게 아니라 다시 get으로 한번더 호출하는 이유가 있을까요?

테스트코드 역시 빠른 속도로 코드가 실행될 수 있게 작성해주셔야 합니다~

2021-01-07 02:20 UTC, lordmyshepherd commented on storage/urls.py
> +    path('/mylistmusic/<int:mylist_id>', MylistMusicView.as_view()),
엔드포인트의 URI가 혼란을 줄 수 있을 것 같습니다.
`/mylistmusic/1 `으로 해당 자원을 명확하게 알 수 있어야되는데 이렇게만 보면 `1`은 mylistmusic 데이터 중에 1번으로 보입니다.
그런데, 실제 로직은 mylist_id를 받고 있네요.

restful하게 수정해주세요~
```suggestion
    path('/mylistmusic/<int:mylist_id>', MylistMusicView.as_view()),
```

2021-01-07 02:20 UTC, lordmyshepherd commented on storage/views.py
> +            mylist      = Mylist.objects.filter(character_id=signed_character.id).filter(id=mylist_id).get()
`signed_character_id` 자세히 설명해주실 수 있나요?

2021-01-07 03:07 UTC, kst6294 commented on storage/tests.py
> +        headers = {'HTTP_Authorization' : self.access_token, 'HTTP_Character' : self.character_id}
해당 flo 사이트에서 사용 하는 모든 기능이 user 를 기반으로 하는 것이 아닌 user 에서 파생된 캐릭터로 정해집니다.

예를 들어 캐릭터를 생성하고 보관함에 노래를 넣을 경우, 캐릭터를 변경하면 보관함 리스트도 변경되게 되는데.

이로 인해 character_id 로 토큰을 생성하지 않고, accesstoken 을 받은 후에, 캐릭터 id 가 존재하면 캐릭터 id를 헤더에 담아서 토큰과 같이 보내주려는 이유입니다.

2021-01-07 03:08 UTC, kst6294 commented on storage/views.py
> +            mylist      = Mylist.objects.filter(character_id=signed_character.id).filter(id=mylist_id).get()
위의 캐릭터 id를 헤더에 넣는 것과 같은 이유로, 헤더에 담긴 id 가 있는 경우에 인증된 캐릭터의 id 를 담아서 filter 할 때 캐릭터를 참조 할 수 있게 했습니다.

2021-01-07 03:15 UTC, kst6294 commented on storage/tests.py
> +            gender=Gender.objects.get(id=1),
반영하겠습니다.

2021-01-07 03:41 UTC, kst6294 commented on storage/urls.py
> +    path('/mylistmusic/<int:mylist_id>', MylistMusicView.as_view()),
반영했습니다.

/mylist/12/music

id가 12인 mylist 의 뮤직을 가져온다고 해석 가능한 restful 엔드포인트로 수정했습니다.

2021-01-07 08:23 UTC, lordmyshepherd commented on storage/tests.py
> +        headers = {'HTTP_Authorization' : self.access_token, 'HTTP_Character' : self.character_id}
이럴 경우에는 데코레이터를 2개로 나눠주세요~

2021-01-07 08:25 UTC, lordmyshepherd requested changes
decorator 부분만 수정해주시면 될 것 같습니다~

2021-01-07 09:18 UTC, kst6294 commented on storage/tests.py
> +        headers = {'HTTP_Authorization' : self.access_token, 'HTTP_Character' : self.character_id}
2개의 데코레이터 ( Character Authorization, SigninAuthorization ) 으로 나누어 합쳤습니다.

2021-01-08 01:49 UTC, lordmyshepherd approved these changes

2021-01-08 01:50 UTC, lordmyshepherd commented
LGTM 👍

2021-01-08 01:50 UTC, merged