[15기 김순태] Add: Signin 기능 구현
wecode-bootcamp-korea/15-2nd-we_ro-backend pull request #9
Opened 2020-12-31 10:54 UTC by kst6294

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- signin 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)
- uservalidation 을 통한 로그인 정보 확인
- Q객체를 활용해서email 과 platform 모두 일치하는 경우만 로그인이 되도록 구현
- test 코드 작성
![image](https://user-images.githubusercontent.com/44313290/103407325-a41b4300-4ba1-11eb-9ccd-f2dc8a388457.png)
- [1] email, platform 모두 일치하는 계정이 있는 경우, [2] email 이 있으나 platfom 이 없는 경우, [3] email, platform 모두 없는 경우, [4] password 가 잘못된 경우
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-01 13:44 UTC, ulfrid requested changes
1월 1일 코드리뷰 늦었습니다. 새해복 많이 받으세요!

2021-01-01 13:44 UTC, ulfrid commented on user/tests.py
> +        access_token = jwt.encode({'id':signed_user.id}, SECRET_KEY, algorithm=ALGORITHM)
이 로직은 실제 Signin 로직 내부에 포함된 부분 아닌가요?  굳이 여기서 실행하는 이유가 있나요?
 엑세스 토큰을 생성해서 비교하지마세요. 
 실제 로그인한후 받은 엑세스 토큰을 담아서 비교해주세요.
 ```
 ex) response = c.post('/users/signin', json.dumps(user), content_type="application/json")
       access_token = response.json()['access_token']
```

2021-01-01 13:44 UTC, ulfrid commented on user/tests.py
> +        access_token = jwt.encode({'id':signed_user.id}, SECRET_KEY, algorithm=ALGORITHM)
다른 테스트 케이스도 마찬가지 입니다.

2021-01-01 13:44 UTC, ulfrid commented on user/views.py
> +            platform = data['platform']
플랫폼으로 가르고 있지만 사실 일반로그인과 소셜 로그인은 아에 분리된 뷰로 처리해야합니다. 향후 소셜 로그인세션을 들으시면 바로 이해하시게 되겠지만, 일단 한번에 처리하기에는 복잡해집니다. 애초에 받아야하는 데이터의 성격이 갈리기 때문입니다.
위의 플랫폼 체크는 변경이 필요할 것 같습니다.

2021-01-01 13:44 UTC, ulfrid commented on user/views.py
> +        except ValueError:
타입이 다른 데이터 전달에 대한 대비 인가요?  조금 직접적이지 않습니다.
Type_checking하는 함수를 만들어 타입에러를 raise하는 코드를 작성해 보시는 건 어떨까요?

2021-01-02 09:34 UTC, kst6294 commented on user/views.py
> +        except ValueError:
이 피드백에 따라 코드를 수정하고 있습니다만... 의도한 대로 진행이 되지 않아, 제가 접근하는 방식이 멘토님이 원하시는 방향과 맞는지 궁금합니다. 
![image](https://user-images.githubusercontent.com/44313290/103454599-0e122480-4d29-11eb-9e00-ae96a1dc0cd4.png)

![image](https://user-images.githubusercontent.com/44313290/103454601-123e4200-4d29-11eb-9d73-d61cb76703fc.png)

2021-01-02 09:35 UTC, kst6294 commented on user/views.py
> +            platform = data['platform']
피드백 확인 후에, 카카오 로그인 테스트를 하면서 굳이 platform 을 구분하는 방식이 의미가 없다고 판단해서 모델과 view에서 삭제했습니다.

2021-01-02 09:36 UTC, kst6294 commented on user/tests.py
> +        access_token = jwt.encode({'id':signed_user.id}, SECRET_KEY, algorithm=ALGORITHM)
확인후에 수정하겠습니다. 

감사합니다.

2021-01-02 09:36 UTC, kst6294 commented
> 1월 1일 코드리뷰 늦었습니다. 새해복 많이 받으세요!

감사합니다.

새해복 많이 받으세요!

2021-01-02 11:08 UTC, ulfrid commented on user/views.py
> +        except ValueError:
오 아닙니다. 
key를 검사하는게 아니라 type을 검사하는 함수를 말씀드렸습니다.
만약 입력받아야 하는 값이 integer인데, string을 대입하면 ValueError가 날거에요. 하지만 이부분은 명확하진 않죠.
그래서 그걸 비교해주는 메소드 아이디어를 말씀드렸습니다.
int를 받아야 하면 int를~ str이면 str을 검사하는 메소드를 말씀드렸습니다. 해보면 좋은 아이디어라서 말씀드렸습니다.

2021-01-03 06:06 UTC, kst6294 commented on user/tests.py
> +        access_token = jwt.encode({'id':signed_user.id}, SECRET_KEY, algorithm=ALGORITHM)
수정했습니다.

2021-01-03 06:06 UTC, kst6294 commented on user/views.py
> +            platform = data['platform']
kakao 로그인을 했을 경우, kakao_id 를 담을 수 있는 column 을 생성했습니다. 일반 로그인의 경우에는 null 로 설정하고자 합니다.

2021-01-03 06:08 UTC, kst6294 commented on user/views.py
> +        except ValueError:
value error 에 한해서 utils.py 타입이 다른 경우에 적용가능한 에러코드를 발생시켰습니다.

2021-01-04 01:57 UTC, ulfrid commented
LGTM.

2021-01-04 01:57 UTC, merged